export interface paths {
  '/v1/forecast': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Open-Meteo Weather Forecast API
     * @description Open-Meteo offers free weather forecast APIs for open-source developers and non-commercial use.
     */
    get: {
      parameters: {
        query: {
          /** @description Geographical WGS84 coordinates. Multiple coordinates can be comma separated. */
          latitude: string;
          longitude: string;
          /** @description A list of weather variables which should be returned. */
          hourly?: (
            | 'temperature_2m'
            | 'temperature_2m_min'
            | 'temperature_2m_max'
            | 'relative_humidity_2m'
            | 'dew_point_2m'
            | 'apparent_temperature'
            | 'precipitation_probability'
            | 'precipitation'
            | 'rain'
            | 'showers'
            | 'snowfall'
            | 'snow_depth'
            | 'snowfall_water_equivalent'
            | 'snow_depth_water_equivalent'
            | 'weather_code'
            | 'pressure_msl'
            | 'surface_pressure'
            | 'cloud_cover'
            | 'cloud_cover_low'
            | 'cloud_cover_mid'
            | 'cloud_cover_high'
            | 'visibility'
            | 'evapotranspiration'
            | 'et0_fao_evapotranspiration'
            | 'vapour_pressure_deficit'
            | 'runoff'
            | 'precipitation_type'
            | 'rain_probability'
            | 'snowfall_probability'
            | 'freezing_rain_probability'
            | 'ice_pellets_probability'
            | 'thunderstorm_probability'
            | 'wind_speed_10m'
            | 'wind_speed_20m'
            | 'wind_speed_30m'
            | 'wind_speed_40m'
            | 'wind_speed_50m'
            | 'wind_speed_70m'
            | 'wind_speed_80m'
            | 'wind_speed_100m'
            | 'wind_speed_120m'
            | 'wind_speed_140m'
            | 'wind_speed_150m'
            | 'wind_speed_160m'
            | 'wind_speed_180m'
            | 'wind_speed_200m'
            | 'wind_direction_10m'
            | 'wind_direction_20m'
            | 'wind_direction_30m'
            | 'wind_direction_40m'
            | 'wind_direction_50m'
            | 'wind_direction_70m'
            | 'wind_direction_80m'
            | 'wind_direction_100m'
            | 'wind_direction_120m'
            | 'wind_direction_140m'
            | 'wind_direction_150m'
            | 'wind_direction_160m'
            | 'wind_direction_180m'
            | 'wind_direction_200m'
            | 'wind_gusts_10m'
            | 'temperature_20m'
            | 'temperature_40m'
            | 'temperature_50m'
            | 'temperature_80m'
            | 'temperature_100m'
            | 'temperature_120m'
            | 'temperature_150m'
            | 'temperature_180m'
            | 'temperature_200m'
            | 'soil_temperature_0cm'
            | 'soil_temperature_6cm'
            | 'soil_temperature_18cm'
            | 'soil_temperature_54cm'
            | 'soil_temperature_162cm'
            | 'soil_temperature_486cm'
            | 'soil_temperature_1458cm'
            | 'soil_temperature_0_to_7cm'
            | 'soil_temperature_7_to_28cm'
            | 'soil_temperature_28_to_100cm'
            | 'soil_temperature_100_to_255cm'
            | 'soil_temperature_0_to_10cm'
            | 'soil_temperature_10_to_40cm'
            | 'soil_temperature_40_to_100cm'
            | 'soil_temperature_100_to_200cm'
            | 'soil_temperature_10_to_35cm'
            | 'soil_temperature_35_to_100cm'
            | 'soil_temperature_100_to_300cm'
            | 'soil_moisture_0_to_1cm'
            | 'soil_moisture_1_to_3cm'
            | 'soil_moisture_3_to_9cm'
            | 'soil_moisture_9_to_27cm'
            | 'soil_moisture_27_to_81cm'
            | 'soil_moisture_81_to_243cm'
            | 'soil_moisture_243_to_729cm'
            | 'soil_moisture_729_to_2187cm'
            | 'soil_moisture_0_to_7cm'
            | 'soil_moisture_7_to_28cm'
            | 'soil_moisture_28_to_100cm'
            | 'soil_moisture_100_to_255cm'
            | 'soil_moisture_0_to_10cm'
            | 'soil_moisture_10_to_40cm'
            | 'soil_moisture_40_to_100cm'
            | 'soil_moisture_100_to_200cm'
            | 'soil_moisture_10_to_35cm'
            | 'soil_moisture_35_to_100cm'
            | 'soil_moisture_100_to_300cm'
            | 'uv_index'
            | 'uv_index_clear_sky'
            | 'is_day'
            | 'sunshine_duration'
            | 'wet_bulb_temperature_2m'
            | 'total_column_integrated_water_vapour'
            | 'cape'
            | 'lifted_index'
            | 'convective_inhibition'
            | 'freezing_level_height'
            | 'boundary_layer_height'
            | 'surface_temperature'
            | 'mass_density_8m'
            | 'snowfall_height'
            | 'convective_cloud_base'
            | 'convective_cloud_top'
            | 'updraft'
            | 'lightning_potential'
            | 'lightning_density'
            | 'snow_height'
            | 'roughness_length'
            | 'albedo'
            | 'k_index'
            | 'sea_level_height_msl'
            | 'sea_ice_thickness'
            | 'sea_surface_temperature'
            | 'ocean_current_velocity'
            | 'ocean_current_direction'
            | 'shortwave_radiation'
            | 'direct_radiation'
            | 'diffuse_radiation'
            | 'direct_normal_irradiance'
            | 'global_tilted_irradiance'
            | 'terrestrial_radiation'
            | 'shortwave_radiation_instant'
            | 'direct_radiation_instant'
            | 'diffuse_radiation_instant'
            | 'direct_normal_irradiance_instant'
            | 'global_tilted_irradiance_instant'
            | 'terrestrial_radiation_instant'
            | 'temperature_1000hPa'
            | 'temperature_950hPa'
            | 'temperature_925hPa'
            | 'temperature_900hPa'
            | 'temperature_850hPa'
            | 'temperature_800hPa'
            | 'temperature_750hPa'
            | 'temperature_700hPa'
            | 'temperature_650hPa'
            | 'temperature_600hPa'
            | 'temperature_550hPa'
            | 'temperature_500hPa'
            | 'temperature_450hPa'
            | 'temperature_400hPa'
            | 'temperature_350hPa'
            | 'temperature_300hPa'
            | 'temperature_275hPa'
            | 'temperature_250hPa'
            | 'temperature_225hPa'
            | 'temperature_200hPa'
            | 'temperature_175hPa'
            | 'temperature_150hPa'
            | 'temperature_125hPa'
            | 'temperature_100hPa'
            | 'temperature_50hPa'
            | 'temperature_10hPa'
            | 'dew_point_1000hPa'
            | 'dew_point_950hPa'
            | 'dew_point_925hPa'
            | 'dew_point_900hPa'
            | 'dew_point_850hPa'
            | 'dew_point_800hPa'
            | 'dew_point_750hPa'
            | 'dew_point_700hPa'
            | 'dew_point_650hPa'
            | 'dew_point_600hPa'
            | 'dew_point_550hPa'
            | 'dew_point_500hPa'
            | 'dew_point_450hPa'
            | 'dew_point_400hPa'
            | 'dew_point_350hPa'
            | 'dew_point_300hPa'
            | 'dew_point_275hPa'
            | 'dew_point_250hPa'
            | 'dew_point_225hPa'
            | 'dew_point_200hPa'
            | 'dew_point_175hPa'
            | 'dew_point_150hPa'
            | 'dew_point_125hPa'
            | 'dew_point_100hPa'
            | 'dew_point_50hPa'
            | 'dew_point_10hPa'
            | 'relative_humidity_1000hPa'
            | 'relative_humidity_950hPa'
            | 'relative_humidity_925hPa'
            | 'relative_humidity_900hPa'
            | 'relative_humidity_850hPa'
            | 'relative_humidity_800hPa'
            | 'relative_humidity_750hPa'
            | 'relative_humidity_700hPa'
            | 'relative_humidity_650hPa'
            | 'relative_humidity_600hPa'
            | 'relative_humidity_550hPa'
            | 'relative_humidity_500hPa'
            | 'relative_humidity_450hPa'
            | 'relative_humidity_400hPa'
            | 'relative_humidity_350hPa'
            | 'relative_humidity_300hPa'
            | 'relative_humidity_275hPa'
            | 'relative_humidity_250hPa'
            | 'relative_humidity_225hPa'
            | 'relative_humidity_200hPa'
            | 'relative_humidity_175hPa'
            | 'relative_humidity_150hPa'
            | 'relative_humidity_125hPa'
            | 'relative_humidity_100hPa'
            | 'relative_humidity_50hPa'
            | 'relative_humidity_10hPa'
            | 'cloud_cover_1000hPa'
            | 'cloud_cover_950hPa'
            | 'cloud_cover_925hPa'
            | 'cloud_cover_900hPa'
            | 'cloud_cover_850hPa'
            | 'cloud_cover_800hPa'
            | 'cloud_cover_750hPa'
            | 'cloud_cover_700hPa'
            | 'cloud_cover_650hPa'
            | 'cloud_cover_600hPa'
            | 'cloud_cover_550hPa'
            | 'cloud_cover_500hPa'
            | 'cloud_cover_450hPa'
            | 'cloud_cover_400hPa'
            | 'cloud_cover_350hPa'
            | 'cloud_cover_300hPa'
            | 'cloud_cover_275hPa'
            | 'cloud_cover_250hPa'
            | 'cloud_cover_225hPa'
            | 'cloud_cover_200hPa'
            | 'cloud_cover_175hPa'
            | 'cloud_cover_150hPa'
            | 'cloud_cover_125hPa'
            | 'cloud_cover_100hPa'
            | 'cloud_cover_50hPa'
            | 'cloud_cover_10hPa'
            | 'wind_speed_1000hPa'
            | 'wind_speed_950hPa'
            | 'wind_speed_925hPa'
            | 'wind_speed_900hPa'
            | 'wind_speed_850hPa'
            | 'wind_speed_800hPa'
            | 'wind_speed_750hPa'
            | 'wind_speed_700hPa'
            | 'wind_speed_650hPa'
            | 'wind_speed_600hPa'
            | 'wind_speed_550hPa'
            | 'wind_speed_500hPa'
            | 'wind_speed_450hPa'
            | 'wind_speed_400hPa'
            | 'wind_speed_350hPa'
            | 'wind_speed_300hPa'
            | 'wind_speed_275hPa'
            | 'wind_speed_250hPa'
            | 'wind_speed_225hPa'
            | 'wind_speed_200hPa'
            | 'wind_speed_175hPa'
            | 'wind_speed_150hPa'
            | 'wind_speed_125hPa'
            | 'wind_speed_100hPa'
            | 'wind_speed_50hPa'
            | 'wind_speed_10hPa'
            | 'wind_direction_1000hPa'
            | 'wind_direction_950hPa'
            | 'wind_direction_925hPa'
            | 'wind_direction_900hPa'
            | 'wind_direction_850hPa'
            | 'wind_direction_800hPa'
            | 'wind_direction_750hPa'
            | 'wind_direction_700hPa'
            | 'wind_direction_650hPa'
            | 'wind_direction_600hPa'
            | 'wind_direction_550hPa'
            | 'wind_direction_500hPa'
            | 'wind_direction_450hPa'
            | 'wind_direction_400hPa'
            | 'wind_direction_350hPa'
            | 'wind_direction_300hPa'
            | 'wind_direction_275hPa'
            | 'wind_direction_250hPa'
            | 'wind_direction_225hPa'
            | 'wind_direction_200hPa'
            | 'wind_direction_175hPa'
            | 'wind_direction_150hPa'
            | 'wind_direction_125hPa'
            | 'wind_direction_100hPa'
            | 'wind_direction_50hPa'
            | 'wind_direction_10hPa'
            | 'vertical_velocity_1000hPa'
            | 'vertical_velocity_950hPa'
            | 'vertical_velocity_925hPa'
            | 'vertical_velocity_900hPa'
            | 'vertical_velocity_850hPa'
            | 'vertical_velocity_800hPa'
            | 'vertical_velocity_750hPa'
            | 'vertical_velocity_700hPa'
            | 'vertical_velocity_650hPa'
            | 'vertical_velocity_600hPa'
            | 'vertical_velocity_550hPa'
            | 'vertical_velocity_500hPa'
            | 'vertical_velocity_450hPa'
            | 'vertical_velocity_400hPa'
            | 'vertical_velocity_350hPa'
            | 'vertical_velocity_300hPa'
            | 'vertical_velocity_275hPa'
            | 'vertical_velocity_250hPa'
            | 'vertical_velocity_225hPa'
            | 'vertical_velocity_200hPa'
            | 'vertical_velocity_175hPa'
            | 'vertical_velocity_150hPa'
            | 'vertical_velocity_125hPa'
            | 'vertical_velocity_100hPa'
            | 'vertical_velocity_50hPa'
            | 'vertical_velocity_10hPa'
            | 'geopotential_height_1000hPa'
            | 'geopotential_height_950hPa'
            | 'geopotential_height_925hPa'
            | 'geopotential_height_900hPa'
            | 'geopotential_height_850hPa'
            | 'geopotential_height_800hPa'
            | 'geopotential_height_750hPa'
            | 'geopotential_height_700hPa'
            | 'geopotential_height_650hPa'
            | 'geopotential_height_600hPa'
            | 'geopotential_height_550hPa'
            | 'geopotential_height_500hPa'
            | 'geopotential_height_450hPa'
            | 'geopotential_height_400hPa'
            | 'geopotential_height_350hPa'
            | 'geopotential_height_300hPa'
            | 'geopotential_height_275hPa'
            | 'geopotential_height_250hPa'
            | 'geopotential_height_225hPa'
            | 'geopotential_height_200hPa'
            | 'geopotential_height_175hPa'
            | 'geopotential_height_150hPa'
            | 'geopotential_height_125hPa'
            | 'geopotential_height_100hPa'
            | 'geopotential_height_50hPa'
            | 'geopotential_height_10hPa'
          )[];
          /** @description A list of daily weather variable aggregations. */
          daily?: (
            | 'weather_code'
            | 'temperature_2m_max'
            | 'temperature_2m_min'
            | 'apparent_temperature_max'
            | 'apparent_temperature_min'
            | 'sunrise'
            | 'sunset'
            | 'daylight_duration'
            | 'sunshine_duration'
            | 'uv_index_max'
            | 'uv_index_clear_sky_max'
            | 'rain_sum'
            | 'showers_sum'
            | 'snowfall_sum'
            | 'precipitation_sum'
            | 'precipitation_hours'
            | 'precipitation_probability_max'
            | 'wind_speed_10m_max'
            | 'wind_gusts_10m_max'
            | 'wind_direction_10m_dominant'
            | 'shortwave_radiation_sum'
            | 'et0_fao_evapotranspiration'
          )[];
          /** @description A list of variables to return for the current conditions. */
          current?: (
            | 'temperature_2m'
            | 'relative_humidity_2m'
            | 'apparent_temperature'
            | 'is_day'
            | 'precipitation'
            | 'rain'
            | 'showers'
            | 'snowfall'
            | 'weather_code'
            | 'cloud_cover'
            | 'pressure_msl'
            | 'surface_pressure'
            | 'wind_speed_10m'
            | 'wind_direction_10m'
            | 'wind_gusts_10m'
          )[];
          /** @description A list of weather variables at 15-minute intervals. */
          minutely_15?: (
            | 'temperature_2m'
            | 'relative_humidity_2m'
            | 'dew_point_2m'
            | 'apparent_temperature'
            | 'precipitation'
            | 'rain'
            | 'snowfall'
            | 'snowfall_height'
            | 'freezing_level_height'
            | 'sunshine_duration'
            | 'weather_code'
            | 'wind_speed_10m'
            | 'wind_speed_20m'
            | 'wind_speed_50m'
            | 'wind_speed_80m'
            | 'wind_speed_100m'
            | 'wind_direction_10m'
            | 'wind_direction_20m'
            | 'wind_direction_50m'
            | 'wind_direction_80m'
            | 'wind_direction_100m'
            | 'wind_gusts_10m'
            | 'visibility'
            | 'cape'
            | 'lightning_potential'
            | 'is_day'
          )[];
          elevation?: number;
          temperature_unit?: 'celsius' | 'fahrenheit';
          wind_speed_unit?: 'kmh' | 'ms' | 'mph' | 'kn';
          precipitation_unit?: 'mm' | 'inch';
          /** @description If format unixtime is selected, all time values are returned in UNIX epoch time. */
          timeformat?: 'iso8601' | 'unixtime';
          /** @description Any IANA time zone name is supported. Use auto to resolve the local time zone. */
          timezone?: string;
          /** @description Return past days of data. */
          past_days?: number;
          /** @description Number of forecast days. */
          forecast_days?: number;
          past_hours?: number;
          forecast_hours?: number;
          /** @description Start date of the time interval in ISO 8601 format. */
          start_date?: string;
          /** @description End date of the time interval in ISO 8601 format. */
          end_date?: string;
          /** @description Slope tilt in degrees for global_tilted_irradiance calculation. */
          tilt?: number;
          /** @description Azimuth for global_tilted_irradiance. North=0, East=90, South=180, West=270. */
          azimuth?: number;
          /** @description Grid cell selection preference: land, sea, or nearest. */
          cell_selection?: 'land' | 'sea' | 'nearest';
          /** @description Only required for commercial subscriptions. */
          apikey?: string;
          /** @description Manually select one or more weather models. */
          models?: (
            | 'best_match'
            | 'ecmwf_ifs'
            | 'ecmwf_ifs025'
            | 'ecmwf_aifs025_single'
            | 'cma_grapes_global'
            | 'bom_access_global'
            | 'gfs_seamless'
            | 'gfs_global'
            | 'gfs_hrrr'
            | 'ncep_nbm_conus'
            | 'ncep_nam_conus'
            | 'gfs_graphcast025'
            | 'ncep_aigfs025'
            | 'ncep_hgefs025_ensemble_mean'
            | 'jma_seamless'
            | 'jma_msm'
            | 'jma_gsm'
            | 'kma_seamless'
            | 'kma_ldps'
            | 'kma_gdps'
            | 'icon_seamless'
            | 'icon_global'
            | 'icon_eu'
            | 'icon_d2'
            | 'gem_seamless'
            | 'gem_global'
            | 'gem_regional'
            | 'gem_hrdps_continental'
            | 'gem_hrdps_west'
            | 'meteofrance_seamless'
            | 'meteofrance_arpege_world'
            | 'meteofrance_arpege_europe'
            | 'meteofrance_arome_france'
            | 'meteofrance_arome_france_hd'
            | 'italia_meteo_arpae_icon_2i'
            | 'metno_seamless'
            | 'metno_nordic'
            | 'knmi_seamless'
            | 'knmi_harmonie_arome_europe'
            | 'knmi_harmonie_arome_netherlands'
            | 'dmi_seamless'
            | 'dmi_harmonie_arome_europe'
            | 'ukmo_seamless'
            | 'ukmo_global_deterministic_10km'
            | 'ukmo_uk_deterministic_2km'
            | 'meteoswiss_icon_seamless'
            | 'meteoswiss_icon_ch1'
            | 'meteoswiss_icon_ch2'
            | 'geosphere_seamless'
            | 'geosphere_arome_austria'
          )[];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: float */
              latitude?: number;
              /** Format: float */
              longitude?: number;
              /** Format: float */
              elevation?: number;
              /** Format: float */
              generationtime_ms?: number;
              utc_offset_seconds?: number;
              timezone?: string;
              timezone_abbreviation?: string;
              hourly?: {
                time?: string[];
                temperature_2m?: number[];
                temperature_2m_min?: number[];
                temperature_2m_max?: number[];
                relative_humidity_2m?: number[];
                dew_point_2m?: number[];
                apparent_temperature?: number[];
                precipitation_probability?: number[];
                precipitation?: number[];
                rain?: number[];
                showers?: number[];
                snowfall?: number[];
                snow_depth?: number[];
                snowfall_water_equivalent?: number[];
                snow_depth_water_equivalent?: number[];
                weather_code?: number[];
                pressure_msl?: number[];
                surface_pressure?: number[];
                cloud_cover?: number[];
                cloud_cover_low?: number[];
                cloud_cover_mid?: number[];
                cloud_cover_high?: number[];
                visibility?: number[];
                evapotranspiration?: number[];
                et0_fao_evapotranspiration?: number[];
                vapour_pressure_deficit?: number[];
                runoff?: number[];
                precipitation_type?: number[];
                rain_probability?: number[];
                snowfall_probability?: number[];
                freezing_rain_probability?: number[];
                ice_pellets_probability?: number[];
                thunderstorm_probability?: number[];
                wind_speed_10m?: number[];
                wind_speed_20m?: number[];
                wind_speed_30m?: number[];
                wind_speed_40m?: number[];
                wind_speed_50m?: number[];
                wind_speed_70m?: number[];
                wind_speed_80m?: number[];
                wind_speed_100m?: number[];
                wind_speed_120m?: number[];
                wind_speed_140m?: number[];
                wind_speed_150m?: number[];
                wind_speed_160m?: number[];
                wind_speed_180m?: number[];
                wind_speed_200m?: number[];
                wind_direction_10m?: number[];
                wind_direction_20m?: number[];
                wind_direction_30m?: number[];
                wind_direction_40m?: number[];
                wind_direction_50m?: number[];
                wind_direction_70m?: number[];
                wind_direction_80m?: number[];
                wind_direction_100m?: number[];
                wind_direction_120m?: number[];
                wind_direction_140m?: number[];
                wind_direction_150m?: number[];
                wind_direction_160m?: number[];
                wind_direction_180m?: number[];
                wind_direction_200m?: number[];
                wind_gusts_10m?: number[];
                temperature_20m?: number[];
                temperature_40m?: number[];
                temperature_50m?: number[];
                temperature_80m?: number[];
                temperature_100m?: number[];
                temperature_120m?: number[];
                temperature_150m?: number[];
                temperature_180m?: number[];
                temperature_200m?: number[];
                soil_temperature_0cm?: number[];
                soil_temperature_6cm?: number[];
                soil_temperature_18cm?: number[];
                soil_temperature_54cm?: number[];
                soil_temperature_162cm?: number[];
                soil_temperature_486cm?: number[];
                soil_temperature_1458cm?: number[];
                soil_temperature_0_to_7cm?: number[];
                soil_temperature_7_to_28cm?: number[];
                soil_temperature_28_to_100cm?: number[];
                soil_temperature_100_to_255cm?: number[];
                soil_temperature_0_to_10cm?: number[];
                soil_temperature_10_to_40cm?: number[];
                soil_temperature_40_to_100cm?: number[];
                soil_temperature_100_to_200cm?: number[];
                soil_temperature_10_to_35cm?: number[];
                soil_temperature_35_to_100cm?: number[];
                soil_temperature_100_to_300cm?: number[];
                soil_moisture_0_to_1cm?: number[];
                soil_moisture_1_to_3cm?: number[];
                soil_moisture_3_to_9cm?: number[];
                soil_moisture_9_to_27cm?: number[];
                soil_moisture_27_to_81cm?: number[];
                soil_moisture_81_to_243cm?: number[];
                soil_moisture_243_to_729cm?: number[];
                soil_moisture_729_to_2187cm?: number[];
                soil_moisture_0_to_7cm?: number[];
                soil_moisture_7_to_28cm?: number[];
                soil_moisture_28_to_100cm?: number[];
                soil_moisture_100_to_255cm?: number[];
                soil_moisture_0_to_10cm?: number[];
                soil_moisture_10_to_40cm?: number[];
                soil_moisture_40_to_100cm?: number[];
                soil_moisture_100_to_200cm?: number[];
                soil_moisture_10_to_35cm?: number[];
                soil_moisture_35_to_100cm?: number[];
                soil_moisture_100_to_300cm?: number[];
                uv_index?: number[];
                uv_index_clear_sky?: number[];
                is_day?: number[];
                sunshine_duration?: number[];
                wet_bulb_temperature_2m?: number[];
                total_column_integrated_water_vapour?: number[];
                cape?: number[];
                lifted_index?: number[];
                convective_inhibition?: number[];
                freezing_level_height?: number[];
                boundary_layer_height?: number[];
                surface_temperature?: number[];
                mass_density_8m?: number[];
                snowfall_height?: number[];
                convective_cloud_base?: number[];
                convective_cloud_top?: number[];
                updraft?: number[];
                lightning_potential?: number[];
                lightning_density?: number[];
                snow_height?: number[];
                roughness_length?: number[];
                albedo?: number[];
                k_index?: number[];
                sea_level_height_msl?: number[];
                sea_ice_thickness?: number[];
                sea_surface_temperature?: number[];
                ocean_current_velocity?: number[];
                ocean_current_direction?: number[];
                shortwave_radiation?: number[];
                direct_radiation?: number[];
                diffuse_radiation?: number[];
                direct_normal_irradiance?: number[];
                global_tilted_irradiance?: number[];
                terrestrial_radiation?: number[];
                shortwave_radiation_instant?: number[];
                direct_radiation_instant?: number[];
                diffuse_radiation_instant?: number[];
                direct_normal_irradiance_instant?: number[];
                global_tilted_irradiance_instant?: number[];
                terrestrial_radiation_instant?: number[];
                temperature_1000hPa?: number[];
                temperature_950hPa?: number[];
                temperature_925hPa?: number[];
                temperature_900hPa?: number[];
                temperature_850hPa?: number[];
                temperature_800hPa?: number[];
                temperature_750hPa?: number[];
                temperature_700hPa?: number[];
                temperature_650hPa?: number[];
                temperature_600hPa?: number[];
                temperature_550hPa?: number[];
                temperature_500hPa?: number[];
                temperature_450hPa?: number[];
                temperature_400hPa?: number[];
                temperature_350hPa?: number[];
                temperature_300hPa?: number[];
                temperature_275hPa?: number[];
                temperature_250hPa?: number[];
                temperature_225hPa?: number[];
                temperature_200hPa?: number[];
                temperature_175hPa?: number[];
                temperature_150hPa?: number[];
                temperature_125hPa?: number[];
                temperature_100hPa?: number[];
                temperature_50hPa?: number[];
                temperature_10hPa?: number[];
                dew_point_1000hPa?: number[];
                dew_point_950hPa?: number[];
                dew_point_925hPa?: number[];
                dew_point_900hPa?: number[];
                dew_point_850hPa?: number[];
                dew_point_800hPa?: number[];
                dew_point_750hPa?: number[];
                dew_point_700hPa?: number[];
                dew_point_650hPa?: number[];
                dew_point_600hPa?: number[];
                dew_point_550hPa?: number[];
                dew_point_500hPa?: number[];
                dew_point_450hPa?: number[];
                dew_point_400hPa?: number[];
                dew_point_350hPa?: number[];
                dew_point_300hPa?: number[];
                dew_point_275hPa?: number[];
                dew_point_250hPa?: number[];
                dew_point_225hPa?: number[];
                dew_point_200hPa?: number[];
                dew_point_175hPa?: number[];
                dew_point_150hPa?: number[];
                dew_point_125hPa?: number[];
                dew_point_100hPa?: number[];
                dew_point_50hPa?: number[];
                dew_point_10hPa?: number[];
                relative_humidity_1000hPa?: number[];
                relative_humidity_950hPa?: number[];
                relative_humidity_925hPa?: number[];
                relative_humidity_900hPa?: number[];
                relative_humidity_850hPa?: number[];
                relative_humidity_800hPa?: number[];
                relative_humidity_750hPa?: number[];
                relative_humidity_700hPa?: number[];
                relative_humidity_650hPa?: number[];
                relative_humidity_600hPa?: number[];
                relative_humidity_550hPa?: number[];
                relative_humidity_500hPa?: number[];
                relative_humidity_450hPa?: number[];
                relative_humidity_400hPa?: number[];
                relative_humidity_350hPa?: number[];
                relative_humidity_300hPa?: number[];
                relative_humidity_275hPa?: number[];
                relative_humidity_250hPa?: number[];
                relative_humidity_225hPa?: number[];
                relative_humidity_200hPa?: number[];
                relative_humidity_175hPa?: number[];
                relative_humidity_150hPa?: number[];
                relative_humidity_125hPa?: number[];
                relative_humidity_100hPa?: number[];
                relative_humidity_50hPa?: number[];
                relative_humidity_10hPa?: number[];
                cloud_cover_1000hPa?: number[];
                cloud_cover_950hPa?: number[];
                cloud_cover_925hPa?: number[];
                cloud_cover_900hPa?: number[];
                cloud_cover_850hPa?: number[];
                cloud_cover_800hPa?: number[];
                cloud_cover_750hPa?: number[];
                cloud_cover_700hPa?: number[];
                cloud_cover_650hPa?: number[];
                cloud_cover_600hPa?: number[];
                cloud_cover_550hPa?: number[];
                cloud_cover_500hPa?: number[];
                cloud_cover_450hPa?: number[];
                cloud_cover_400hPa?: number[];
                cloud_cover_350hPa?: number[];
                cloud_cover_300hPa?: number[];
                cloud_cover_275hPa?: number[];
                cloud_cover_250hPa?: number[];
                cloud_cover_225hPa?: number[];
                cloud_cover_200hPa?: number[];
                cloud_cover_175hPa?: number[];
                cloud_cover_150hPa?: number[];
                cloud_cover_125hPa?: number[];
                cloud_cover_100hPa?: number[];
                cloud_cover_50hPa?: number[];
                cloud_cover_10hPa?: number[];
                wind_speed_1000hPa?: number[];
                wind_speed_950hPa?: number[];
                wind_speed_925hPa?: number[];
                wind_speed_900hPa?: number[];
                wind_speed_850hPa?: number[];
                wind_speed_800hPa?: number[];
                wind_speed_750hPa?: number[];
                wind_speed_700hPa?: number[];
                wind_speed_650hPa?: number[];
                wind_speed_600hPa?: number[];
                wind_speed_550hPa?: number[];
                wind_speed_500hPa?: number[];
                wind_speed_450hPa?: number[];
                wind_speed_400hPa?: number[];
                wind_speed_350hPa?: number[];
                wind_speed_300hPa?: number[];
                wind_speed_275hPa?: number[];
                wind_speed_250hPa?: number[];
                wind_speed_225hPa?: number[];
                wind_speed_200hPa?: number[];
                wind_speed_175hPa?: number[];
                wind_speed_150hPa?: number[];
                wind_speed_125hPa?: number[];
                wind_speed_100hPa?: number[];
                wind_speed_50hPa?: number[];
                wind_speed_10hPa?: number[];
                wind_direction_1000hPa?: number[];
                wind_direction_950hPa?: number[];
                wind_direction_925hPa?: number[];
                wind_direction_900hPa?: number[];
                wind_direction_850hPa?: number[];
                wind_direction_800hPa?: number[];
                wind_direction_750hPa?: number[];
                wind_direction_700hPa?: number[];
                wind_direction_650hPa?: number[];
                wind_direction_600hPa?: number[];
                wind_direction_550hPa?: number[];
                wind_direction_500hPa?: number[];
                wind_direction_450hPa?: number[];
                wind_direction_400hPa?: number[];
                wind_direction_350hPa?: number[];
                wind_direction_300hPa?: number[];
                wind_direction_275hPa?: number[];
                wind_direction_250hPa?: number[];
                wind_direction_225hPa?: number[];
                wind_direction_200hPa?: number[];
                wind_direction_175hPa?: number[];
                wind_direction_150hPa?: number[];
                wind_direction_125hPa?: number[];
                wind_direction_100hPa?: number[];
                wind_direction_50hPa?: number[];
                wind_direction_10hPa?: number[];
                vertical_velocity_1000hPa?: number[];
                vertical_velocity_950hPa?: number[];
                vertical_velocity_925hPa?: number[];
                vertical_velocity_900hPa?: number[];
                vertical_velocity_850hPa?: number[];
                vertical_velocity_800hPa?: number[];
                vertical_velocity_750hPa?: number[];
                vertical_velocity_700hPa?: number[];
                vertical_velocity_650hPa?: number[];
                vertical_velocity_600hPa?: number[];
                vertical_velocity_550hPa?: number[];
                vertical_velocity_500hPa?: number[];
                vertical_velocity_450hPa?: number[];
                vertical_velocity_400hPa?: number[];
                vertical_velocity_350hPa?: number[];
                vertical_velocity_300hPa?: number[];
                vertical_velocity_275hPa?: number[];
                vertical_velocity_250hPa?: number[];
                vertical_velocity_225hPa?: number[];
                vertical_velocity_200hPa?: number[];
                vertical_velocity_175hPa?: number[];
                vertical_velocity_150hPa?: number[];
                vertical_velocity_125hPa?: number[];
                vertical_velocity_100hPa?: number[];
                vertical_velocity_50hPa?: number[];
                vertical_velocity_10hPa?: number[];
                geopotential_height_1000hPa?: number[];
                geopotential_height_950hPa?: number[];
                geopotential_height_925hPa?: number[];
                geopotential_height_900hPa?: number[];
                geopotential_height_850hPa?: number[];
                geopotential_height_800hPa?: number[];
                geopotential_height_750hPa?: number[];
                geopotential_height_700hPa?: number[];
                geopotential_height_650hPa?: number[];
                geopotential_height_600hPa?: number[];
                geopotential_height_550hPa?: number[];
                geopotential_height_500hPa?: number[];
                geopotential_height_450hPa?: number[];
                geopotential_height_400hPa?: number[];
                geopotential_height_350hPa?: number[];
                geopotential_height_300hPa?: number[];
                geopotential_height_275hPa?: number[];
                geopotential_height_250hPa?: number[];
                geopotential_height_225hPa?: number[];
                geopotential_height_200hPa?: number[];
                geopotential_height_175hPa?: number[];
                geopotential_height_150hPa?: number[];
                geopotential_height_125hPa?: number[];
                geopotential_height_100hPa?: number[];
                geopotential_height_50hPa?: number[];
                geopotential_height_10hPa?: number[];
              };
              hourly_units?: {
                time?: string;
                temperature_2m?: string;
                temperature_2m_min?: string;
                temperature_2m_max?: string;
                relative_humidity_2m?: string;
                dew_point_2m?: string;
                apparent_temperature?: string;
                precipitation_probability?: string;
                precipitation?: string;
                rain?: string;
                showers?: string;
                snowfall?: string;
                snow_depth?: string;
                snowfall_water_equivalent?: string;
                snow_depth_water_equivalent?: string;
                weather_code?: string;
                pressure_msl?: string;
                surface_pressure?: string;
                cloud_cover?: string;
                cloud_cover_low?: string;
                cloud_cover_mid?: string;
                cloud_cover_high?: string;
                visibility?: string;
                evapotranspiration?: string;
                et0_fao_evapotranspiration?: string;
                vapour_pressure_deficit?: string;
                runoff?: string;
                precipitation_type?: string;
                rain_probability?: string;
                snowfall_probability?: string;
                freezing_rain_probability?: string;
                ice_pellets_probability?: string;
                thunderstorm_probability?: string;
                wind_speed_10m?: string;
                wind_speed_20m?: string;
                wind_speed_30m?: string;
                wind_speed_40m?: string;
                wind_speed_50m?: string;
                wind_speed_70m?: string;
                wind_speed_80m?: string;
                wind_speed_100m?: string;
                wind_speed_120m?: string;
                wind_speed_140m?: string;
                wind_speed_150m?: string;
                wind_speed_160m?: string;
                wind_speed_180m?: string;
                wind_speed_200m?: string;
                wind_direction_10m?: string;
                wind_direction_20m?: string;
                wind_direction_30m?: string;
                wind_direction_40m?: string;
                wind_direction_50m?: string;
                wind_direction_70m?: string;
                wind_direction_80m?: string;
                wind_direction_100m?: string;
                wind_direction_120m?: string;
                wind_direction_140m?: string;
                wind_direction_150m?: string;
                wind_direction_160m?: string;
                wind_direction_180m?: string;
                wind_direction_200m?: string;
                wind_gusts_10m?: string;
                temperature_20m?: string;
                temperature_40m?: string;
                temperature_50m?: string;
                temperature_80m?: string;
                temperature_100m?: string;
                temperature_120m?: string;
                temperature_150m?: string;
                temperature_180m?: string;
                temperature_200m?: string;
                soil_temperature_0cm?: string;
                soil_temperature_6cm?: string;
                soil_temperature_18cm?: string;
                soil_temperature_54cm?: string;
                soil_temperature_162cm?: string;
                soil_temperature_486cm?: string;
                soil_temperature_1458cm?: string;
                soil_temperature_0_to_7cm?: string;
                soil_temperature_7_to_28cm?: string;
                soil_temperature_28_to_100cm?: string;
                soil_temperature_100_to_255cm?: string;
                soil_temperature_0_to_10cm?: string;
                soil_temperature_10_to_40cm?: string;
                soil_temperature_40_to_100cm?: string;
                soil_temperature_100_to_200cm?: string;
                soil_temperature_10_to_35cm?: string;
                soil_temperature_35_to_100cm?: string;
                soil_temperature_100_to_300cm?: string;
                soil_moisture_0_to_1cm?: string;
                soil_moisture_1_to_3cm?: string;
                soil_moisture_3_to_9cm?: string;
                soil_moisture_9_to_27cm?: string;
                soil_moisture_27_to_81cm?: string;
                soil_moisture_81_to_243cm?: string;
                soil_moisture_243_to_729cm?: string;
                soil_moisture_729_to_2187cm?: string;
                soil_moisture_0_to_7cm?: string;
                soil_moisture_7_to_28cm?: string;
                soil_moisture_28_to_100cm?: string;
                soil_moisture_100_to_255cm?: string;
                soil_moisture_0_to_10cm?: string;
                soil_moisture_10_to_40cm?: string;
                soil_moisture_40_to_100cm?: string;
                soil_moisture_100_to_200cm?: string;
                soil_moisture_10_to_35cm?: string;
                soil_moisture_35_to_100cm?: string;
                soil_moisture_100_to_300cm?: string;
                uv_index?: string;
                uv_index_clear_sky?: string;
                is_day?: string;
                sunshine_duration?: string;
                wet_bulb_temperature_2m?: string;
                total_column_integrated_water_vapour?: string;
                cape?: string;
                lifted_index?: string;
                convective_inhibition?: string;
                freezing_level_height?: string;
                boundary_layer_height?: string;
                surface_temperature?: string;
                mass_density_8m?: string;
                snowfall_height?: string;
                convective_cloud_base?: string;
                convective_cloud_top?: string;
                updraft?: string;
                lightning_potential?: string;
                lightning_density?: string;
                snow_height?: string;
                roughness_length?: string;
                albedo?: string;
                k_index?: string;
                sea_level_height_msl?: string;
                sea_ice_thickness?: string;
                sea_surface_temperature?: string;
                ocean_current_velocity?: string;
                ocean_current_direction?: string;
                shortwave_radiation?: string;
                direct_radiation?: string;
                diffuse_radiation?: string;
                direct_normal_irradiance?: string;
                global_tilted_irradiance?: string;
                terrestrial_radiation?: string;
                shortwave_radiation_instant?: string;
                direct_radiation_instant?: string;
                diffuse_radiation_instant?: string;
                direct_normal_irradiance_instant?: string;
                global_tilted_irradiance_instant?: string;
                terrestrial_radiation_instant?: string;
                temperature_1000hPa?: string;
                temperature_950hPa?: string;
                temperature_925hPa?: string;
                temperature_900hPa?: string;
                temperature_850hPa?: string;
                temperature_800hPa?: string;
                temperature_750hPa?: string;
                temperature_700hPa?: string;
                temperature_650hPa?: string;
                temperature_600hPa?: string;
                temperature_550hPa?: string;
                temperature_500hPa?: string;
                temperature_450hPa?: string;
                temperature_400hPa?: string;
                temperature_350hPa?: string;
                temperature_300hPa?: string;
                temperature_275hPa?: string;
                temperature_250hPa?: string;
                temperature_225hPa?: string;
                temperature_200hPa?: string;
                temperature_175hPa?: string;
                temperature_150hPa?: string;
                temperature_125hPa?: string;
                temperature_100hPa?: string;
                temperature_50hPa?: string;
                temperature_10hPa?: string;
                dew_point_1000hPa?: string;
                dew_point_950hPa?: string;
                dew_point_925hPa?: string;
                dew_point_900hPa?: string;
                dew_point_850hPa?: string;
                dew_point_800hPa?: string;
                dew_point_750hPa?: string;
                dew_point_700hPa?: string;
                dew_point_650hPa?: string;
                dew_point_600hPa?: string;
                dew_point_550hPa?: string;
                dew_point_500hPa?: string;
                dew_point_450hPa?: string;
                dew_point_400hPa?: string;
                dew_point_350hPa?: string;
                dew_point_300hPa?: string;
                dew_point_275hPa?: string;
                dew_point_250hPa?: string;
                dew_point_225hPa?: string;
                dew_point_200hPa?: string;
                dew_point_175hPa?: string;
                dew_point_150hPa?: string;
                dew_point_125hPa?: string;
                dew_point_100hPa?: string;
                dew_point_50hPa?: string;
                dew_point_10hPa?: string;
                relative_humidity_1000hPa?: string;
                relative_humidity_950hPa?: string;
                relative_humidity_925hPa?: string;
                relative_humidity_900hPa?: string;
                relative_humidity_850hPa?: string;
                relative_humidity_800hPa?: string;
                relative_humidity_750hPa?: string;
                relative_humidity_700hPa?: string;
                relative_humidity_650hPa?: string;
                relative_humidity_600hPa?: string;
                relative_humidity_550hPa?: string;
                relative_humidity_500hPa?: string;
                relative_humidity_450hPa?: string;
                relative_humidity_400hPa?: string;
                relative_humidity_350hPa?: string;
                relative_humidity_300hPa?: string;
                relative_humidity_275hPa?: string;
                relative_humidity_250hPa?: string;
                relative_humidity_225hPa?: string;
                relative_humidity_200hPa?: string;
                relative_humidity_175hPa?: string;
                relative_humidity_150hPa?: string;
                relative_humidity_125hPa?: string;
                relative_humidity_100hPa?: string;
                relative_humidity_50hPa?: string;
                relative_humidity_10hPa?: string;
                cloud_cover_1000hPa?: string;
                cloud_cover_950hPa?: string;
                cloud_cover_925hPa?: string;
                cloud_cover_900hPa?: string;
                cloud_cover_850hPa?: string;
                cloud_cover_800hPa?: string;
                cloud_cover_750hPa?: string;
                cloud_cover_700hPa?: string;
                cloud_cover_650hPa?: string;
                cloud_cover_600hPa?: string;
                cloud_cover_550hPa?: string;
                cloud_cover_500hPa?: string;
                cloud_cover_450hPa?: string;
                cloud_cover_400hPa?: string;
                cloud_cover_350hPa?: string;
                cloud_cover_300hPa?: string;
                cloud_cover_275hPa?: string;
                cloud_cover_250hPa?: string;
                cloud_cover_225hPa?: string;
                cloud_cover_200hPa?: string;
                cloud_cover_175hPa?: string;
                cloud_cover_150hPa?: string;
                cloud_cover_125hPa?: string;
                cloud_cover_100hPa?: string;
                cloud_cover_50hPa?: string;
                cloud_cover_10hPa?: string;
                wind_speed_1000hPa?: string;
                wind_speed_950hPa?: string;
                wind_speed_925hPa?: string;
                wind_speed_900hPa?: string;
                wind_speed_850hPa?: string;
                wind_speed_800hPa?: string;
                wind_speed_750hPa?: string;
                wind_speed_700hPa?: string;
                wind_speed_650hPa?: string;
                wind_speed_600hPa?: string;
                wind_speed_550hPa?: string;
                wind_speed_500hPa?: string;
                wind_speed_450hPa?: string;
                wind_speed_400hPa?: string;
                wind_speed_350hPa?: string;
                wind_speed_300hPa?: string;
                wind_speed_275hPa?: string;
                wind_speed_250hPa?: string;
                wind_speed_225hPa?: string;
                wind_speed_200hPa?: string;
                wind_speed_175hPa?: string;
                wind_speed_150hPa?: string;
                wind_speed_125hPa?: string;
                wind_speed_100hPa?: string;
                wind_speed_50hPa?: string;
                wind_speed_10hPa?: string;
                wind_direction_1000hPa?: string;
                wind_direction_950hPa?: string;
                wind_direction_925hPa?: string;
                wind_direction_900hPa?: string;
                wind_direction_850hPa?: string;
                wind_direction_800hPa?: string;
                wind_direction_750hPa?: string;
                wind_direction_700hPa?: string;
                wind_direction_650hPa?: string;
                wind_direction_600hPa?: string;
                wind_direction_550hPa?: string;
                wind_direction_500hPa?: string;
                wind_direction_450hPa?: string;
                wind_direction_400hPa?: string;
                wind_direction_350hPa?: string;
                wind_direction_300hPa?: string;
                wind_direction_275hPa?: string;
                wind_direction_250hPa?: string;
                wind_direction_225hPa?: string;
                wind_direction_200hPa?: string;
                wind_direction_175hPa?: string;
                wind_direction_150hPa?: string;
                wind_direction_125hPa?: string;
                wind_direction_100hPa?: string;
                wind_direction_50hPa?: string;
                wind_direction_10hPa?: string;
                vertical_velocity_1000hPa?: string;
                vertical_velocity_950hPa?: string;
                vertical_velocity_925hPa?: string;
                vertical_velocity_900hPa?: string;
                vertical_velocity_850hPa?: string;
                vertical_velocity_800hPa?: string;
                vertical_velocity_750hPa?: string;
                vertical_velocity_700hPa?: string;
                vertical_velocity_650hPa?: string;
                vertical_velocity_600hPa?: string;
                vertical_velocity_550hPa?: string;
                vertical_velocity_500hPa?: string;
                vertical_velocity_450hPa?: string;
                vertical_velocity_400hPa?: string;
                vertical_velocity_350hPa?: string;
                vertical_velocity_300hPa?: string;
                vertical_velocity_275hPa?: string;
                vertical_velocity_250hPa?: string;
                vertical_velocity_225hPa?: string;
                vertical_velocity_200hPa?: string;
                vertical_velocity_175hPa?: string;
                vertical_velocity_150hPa?: string;
                vertical_velocity_125hPa?: string;
                vertical_velocity_100hPa?: string;
                vertical_velocity_50hPa?: string;
                vertical_velocity_10hPa?: string;
                geopotential_height_1000hPa?: string;
                geopotential_height_950hPa?: string;
                geopotential_height_925hPa?: string;
                geopotential_height_900hPa?: string;
                geopotential_height_850hPa?: string;
                geopotential_height_800hPa?: string;
                geopotential_height_750hPa?: string;
                geopotential_height_700hPa?: string;
                geopotential_height_650hPa?: string;
                geopotential_height_600hPa?: string;
                geopotential_height_550hPa?: string;
                geopotential_height_500hPa?: string;
                geopotential_height_450hPa?: string;
                geopotential_height_400hPa?: string;
                geopotential_height_350hPa?: string;
                geopotential_height_300hPa?: string;
                geopotential_height_275hPa?: string;
                geopotential_height_250hPa?: string;
                geopotential_height_225hPa?: string;
                geopotential_height_200hPa?: string;
                geopotential_height_175hPa?: string;
                geopotential_height_150hPa?: string;
                geopotential_height_125hPa?: string;
                geopotential_height_100hPa?: string;
                geopotential_height_50hPa?: string;
                geopotential_height_10hPa?: string;
              };
              daily?: {
                time?: string[];
                weather_code?: number[];
                temperature_2m_max?: number[];
                temperature_2m_min?: number[];
                apparent_temperature_max?: number[];
                apparent_temperature_min?: number[];
                sunrise?: string[];
                sunset?: string[];
                daylight_duration?: number[];
                sunshine_duration?: number[];
                uv_index_max?: number[];
                uv_index_clear_sky_max?: number[];
                rain_sum?: number[];
                showers_sum?: number[];
                snowfall_sum?: number[];
                precipitation_sum?: number[];
                precipitation_hours?: number[];
                precipitation_probability_max?: number[];
                wind_speed_10m_max?: number[];
                wind_gusts_10m_max?: number[];
                wind_direction_10m_dominant?: number[];
                shortwave_radiation_sum?: number[];
                et0_fao_evapotranspiration?: number[];
              };
              daily_units?: {
                time?: string;
                weather_code?: string;
                temperature_2m_max?: string;
                temperature_2m_min?: string;
                apparent_temperature_max?: string;
                apparent_temperature_min?: string;
                sunrise?: string;
                sunset?: string;
                daylight_duration?: string;
                sunshine_duration?: string;
                uv_index_max?: string;
                uv_index_clear_sky_max?: string;
                rain_sum?: string;
                showers_sum?: string;
                snowfall_sum?: string;
                precipitation_sum?: string;
                precipitation_hours?: string;
                precipitation_probability_max?: string;
                wind_speed_10m_max?: string;
                wind_gusts_10m_max?: string;
                wind_direction_10m_dominant?: string;
                shortwave_radiation_sum?: string;
                et0_fao_evapotranspiration?: string;
              };
              current?: {
                time?: string;
                interval?: number;
                /** Format: float */
                temperature_2m?: number;
                /** Format: float */
                relative_humidity_2m?: number;
                /** Format: float */
                apparent_temperature?: number;
                is_day?: number;
                /** Format: float */
                precipitation?: number;
                /** Format: float */
                rain?: number;
                /** Format: float */
                showers?: number;
                /** Format: float */
                snowfall?: number;
                weather_code?: number;
                /** Format: float */
                cloud_cover?: number;
                /** Format: float */
                pressure_msl?: number;
                /** Format: float */
                surface_pressure?: number;
                /** Format: float */
                wind_speed_10m?: number;
                /** Format: float */
                wind_direction_10m?: number;
                /** Format: float */
                wind_gusts_10m?: number;
              };
              current_units?: {
                time?: string;
                temperature_2m?: string;
                relative_humidity_2m?: string;
                apparent_temperature?: string;
                is_day?: string;
                precipitation?: string;
                rain?: string;
                showers?: string;
                snowfall?: string;
                weather_code?: string;
                cloud_cover?: string;
                pressure_msl?: string;
                surface_pressure?: string;
                wind_speed_10m?: string;
                wind_direction_10m?: string;
                wind_gusts_10m?: string;
              };
              minutely_15?: {
                time?: string[];
                temperature_2m?: number[];
                relative_humidity_2m?: number[];
                dew_point_2m?: number[];
                apparent_temperature?: number[];
                precipitation?: number[];
                rain?: number[];
                snowfall?: number[];
                snowfall_height?: number[];
                freezing_level_height?: number[];
                sunshine_duration?: number[];
                weather_code?: number[];
                wind_speed_10m?: number[];
                wind_speed_20m?: number[];
                wind_speed_50m?: number[];
                wind_speed_80m?: number[];
                wind_speed_100m?: number[];
                wind_direction_10m?: number[];
                wind_direction_20m?: number[];
                wind_direction_50m?: number[];
                wind_direction_80m?: number[];
                wind_direction_100m?: number[];
                wind_gusts_10m?: number[];
                visibility?: number[];
                cape?: number[];
                lightning_potential?: number[];
                is_day?: number[];
              };
              minutely_15_units?: {
                time?: string;
                temperature_2m?: string;
                relative_humidity_2m?: string;
                dew_point_2m?: string;
                apparent_temperature?: string;
                precipitation?: string;
                rain?: string;
                snowfall?: string;
                snowfall_height?: string;
                freezing_level_height?: string;
                sunshine_duration?: string;
                weather_code?: string;
                wind_speed_10m?: string;
                wind_speed_20m?: string;
                wind_speed_50m?: string;
                wind_speed_80m?: string;
                wind_speed_100m?: string;
                wind_direction_10m?: string;
                wind_direction_20m?: string;
                wind_direction_50m?: string;
                wind_direction_80m?: string;
                wind_direction_100m?: string;
                wind_gusts_10m?: string;
                visibility?: string;
                cape?: string;
                lightning_potential?: string;
                is_day?: string;
              };
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: boolean;
              reason?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
