/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = T | U extends object
  ? (Without<T, U> & U) | (Without<U, T> & T)
  : T | U;
type OneOf<T extends any[]> = T extends [infer Only]
  ? Only
  : T extends [infer A, infer B, ...infer Rest]
    ? OneOf<[XOR<A, B>, ...Rest]>
    : never;

export interface paths {
  '/stations': {
    /**
     * Get a list of train stations
     * @description Returns a paginated and searchable list of all train stations.
     */
    get: operations['get-stations'];
  };
  '/trips': {
    /**
     * Get available train trips
     * @description Returns a list of available train trips between the specified origin and destination stations on the given date, and allows for filtering by bicycle and dog allowances.
     */
    get: operations['get-trips'];
  };
  '/bookings': {
    /**
     * List existing bookings
     * @description Returns a list of all trip bookings by the authenticated user.
     */
    get: operations['get-bookings'];
    /**
     * Create a booking
     * @description A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
     */
    post: operations['create-booking'];
  };
  '/bookings/{bookingId}': {
    /**
     * Get a booking
     * @description Returns the details of a specific booking.
     */
    get: operations['get-booking'];
    /**
     * Delete a booking
     * @description Deletes a booking, cancelling the hold on the trip.
     */
    delete: operations['delete-booking'];
    parameters: {
      path: {
        /**
         * @description The ID of the booking to retrieve.
         * @example 1725ff48-ab45-4bb5-9d02-88745177dedb
         */
        bookingId: string;
      };
    };
  };
  '/bookings/{bookingId}/payment': {
    /**
     * Pay for a Booking
     * @description A payment is an attempt to pay for the booking, which will confirm the booking for the user and enable them to get their tickets.
     */
    post: operations['create-booking-payment'];
    parameters: {
      path: {
        /**
         * @description The ID of the booking to pay for.
         * @example 1725ff48-ab45-4bb5-9d02-88745177dedb
         */
        bookingId: string;
      };
    };
  };
}

export interface webhooks {
  newBooking: {
    /**
     * New Booking
     * @description Subscribe to new bookings being created, to update integrations for your users.  Related data is available via the links provided in the request.
     */
    post: operations['new-booking'];
  };
}

export interface components {
  schemas: {
    /** @description A train station. */
    Station: {
      /**
       * Format: uuid
       * @description Unique identifier for the station.
       */
      id: string;
      /** @description The name of the station */
      name: string;
      /** @description The address of the station. */
      address: string;
      /**
       * Format: iso-country-code
       * @description The country code of the station.
       */
      country_code: string;
      /** @description The timezone of the station in the [IANA Time Zone Database format](https://www.iana.org/time-zones). */
      timezone?: string;
    };
    /** @description The link to the current resource. */
    'Links-Self': {
      /** Format: uri */
      self?: string;
    };
    /** @description The link to the destination station resource. */
    'Links-Destination': {
      /** Format: uri */
      self?: string;
    };
    /** @description The link to the origin station resource. */
    'Links-Origin': {
      /** Format: uri */
      self?: string;
    };
    /** @description Links to the next and previous pages of a paginated response. */
    'Links-Pagination': {
      /** Format: uri */
      next?: string;
      /** Format: uri */
      prev?: string;
    };
    /** @description A problem detail object as defined in RFC 7807. */
    Problem: {
      /** @description A URI reference that identifies the problem type */
      type?: string;
      /** @description A short, human-readable summary of the problem type */
      title?: string;
      /** @description A human-readable explanation specific to this occurrence of the problem */
      detail?: string;
      /** @description A URI reference that identifies the specific occurrence of the problem */
      instance?: string;
      /** @description The HTTP status code */
      status?: number;
    };
    /** @description A train trip. */
    Trip: {
      /**
       * Format: uuid
       * @description Unique identifier for the trip
       */
      id?: string;
      /** @description The starting station of the trip */
      origin?: string;
      /** @description The destination station of the trip */
      destination?: string;
      /**
       * Format: date-time
       * @description The date and time when the trip departs
       */
      departure_time?: string;
      /**
       * Format: date-time
       * @description The date and time when the trip arrives
       */
      arrival_time?: string;
      /** @description The name of the operator of the trip */
      operator?: string;
      /** @description The cost of the trip */
      price?: number;
      /** @description Indicates whether bicycles are allowed on the trip */
      bicycles_allowed?: boolean;
      /** @description Indicates whether dogs are allowed on the trip */
      dogs_allowed?: boolean;
    };
    /** @description A booking for a train trip. */
    Booking: {
      /**
       * Format: uuid
       * @description Unique identifier for the booking
       */
      id?: string;
      /**
       * Format: uuid
       * @description Identifier of the booked trip
       */
      trip_id?: string;
      /** @description Name of the passenger */
      passenger_name?: string;
      /** @description Indicates whether the passenger has a bicycle. */
      has_bicycle?: boolean;
      /** @description Indicates whether the passenger has a dog. */
      has_dog?: boolean;
    };
    /** @description This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS). */
    'Wrapper-Collection': {
      /** @description The wrapper for a collection is an array of objects. */
      data?: Record<string, never>[];
      /** @description A set of hypermedia links which serve as controls for the client. */
      links?: Record<string, never>;
    };
    /** @description A payment for a booking. */
    BookingPayment: {
      /**
       * Format: uuid
       * @description Unique identifier for the payment. This will be a unique identifier for the payment, and is used to reference the payment in other objects.
       */
      id?: string;
      /** @description Amount intended to be collected by this payment. A positive decimal figure describing the amount to be collected. */
      amount?: number;
      /**
       * @description Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
       * @enum {string}
       */
      currency?: 'bam' | 'bgn' | 'chf' | 'eur' | 'gbp' | 'nok' | 'sek' | 'try';
      /** @description The payment source to take the payment from. This can be a card or a bank account. Some of these properties will be hidden on read to protect PII leaking. */
      source?: OneOf<
        [
          {
            /** @constant */
            object?: 'card';
            /** @description Cardholder's full name as it appears on the card. */
            name: string;
            /** @description The card number, as a string without any separators. On read all but the last four digits will be masked for security. */
            number: string;
            /**
             * @description Card security code, 3 or 4 digits usually found on the back of the card.
             * @example 123
             */
            cvc: string;
            /**
             * Format: int64
             * @description Two-digit number representing the card's expiration month.
             */
            exp_month: number;
            /**
             * Format: int64
             * @description Four-digit number representing the card's expiration year.
             */
            exp_year: number;
            address_line1?: string;
            address_line2?: string;
            address_city?: string;
            address_country: string;
            address_post_code?: string;
          },
          {
            /** @constant */
            object?: 'bank_account';
            name: string;
            /** @description The account number for the bank account, in string form. Must be a current account. */
            number: string;
            /** @description The sort code for the bank account, in string form. Must be a six-digit number. */
            sort_code?: string;
            /**
             * @description The type of entity that holds the account. This can be either `individual` or `company`.
             * @enum {string}
             */
            account_type: 'individual' | 'company';
            /** @description The name of the bank associated with the routing number. */
            bank_name: string;
            /** @description Two-letter country code (ISO 3166-1 alpha-2). */
            country: string;
          },
        ]
      >;
      /**
       * @description The status of the payment, one of `pending`, `succeeded`, or `failed`.
       * @enum {string}
       */
      status?: 'pending' | 'succeeded' | 'failed';
    };
    /** @description The link to the booking resource. */
    'Links-Booking': {
      /** Format: uri */
      booking?: string;
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
    /** @description Conflict */
    Conflict: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
    /** @description Not Found */
    NotFound: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
        'Retry-After': components['headers']['Retry-After'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        RateLimit: components['headers']['RateLimit'];
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
        'application/problem+xml': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    /**
     * @description The page number to return
     * @example 1
     */
    page?: number;
    /**
     * @description The number of items to return per page
     * @example 10
     */
    limit?: number;
  };
  requestBodies: never;
  headers: {
    /**
     * @description The Cache-Control header communicates directives for caching mechanisms in both requests and responses.
     * It is used to specify the caching directives in responses to prevent caches from storing sensitive information.
     */
    'Cache-Control': string;
    /**
     * @description The RateLimit header communicates quota policies. It contains a `limit` to
     * convey the expiring limit, `remaining` to convey the remaining quota units,
     * and `reset` to convey the time window reset time.
     */
    RateLimit: string;
    /**
     * @description The Retry-After header indicates how long the user agent should wait before making a follow-up request.
     * The value is in seconds and can be an integer or a date in the future.
     * If the value is an integer, it indicates the number of seconds to wait.
     * If the value is a date, it indicates the time at which the user agent should make a follow-up request.
     */
    'Retry-After': string;
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Get a list of train stations
   * @description Returns a paginated and searchable list of all train stations.
   */
  'get-stations': {
    parameters: {
      query?: {
        page?: components['parameters']['page'];
        limit?: components['parameters']['limit'];
        /**
         * @description The latitude and longitude of the user's location, to narrow down the search results to sites within a proximity of this location.
         *
         * @example 52.5200,13.4050
         */
        coordinates?: string;
        /** @description A search term to filter the list of stations by name or address. */
        search?: string;
        /**
         * @description Filter stations by country code
         * @example DE
         */
        country?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Cache-Control': components['headers']['Cache-Control'];
          RateLimit: components['headers']['RateLimit'];
        };
        content: {
          'application/json': components['schemas']['Wrapper-Collection'] & {
            data?: components['schemas']['Station'][];
          } & {
            links?: components['schemas']['Links-Self'] &
              components['schemas']['Links-Pagination'];
          };
          'application/xml': components['schemas']['Wrapper-Collection'] & {
            data?: components['schemas']['Station'][];
          } & {
            links?: components['schemas']['Links-Self'] &
              components['schemas']['Links-Pagination'];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Get available train trips
   * @description Returns a list of available train trips between the specified origin and destination stations on the given date, and allows for filtering by bicycle and dog allowances.
   */
  'get-trips': {
    parameters: {
      query: {
        page?: components['parameters']['page'];
        limit?: components['parameters']['limit'];
        /**
         * @description The ID of the origin station
         * @example efdbb9d1-02c2-4bc3-afb7-6788d8782b1e
         */
        origin: string;
        /**
         * @description The ID of the destination station
         * @example b2e783e1-c824-4d63-b37a-d8d698862f1d
         */
        destination: string;
        /**
         * @description The date and time of the trip in ISO 8601 format in origin station's timezone.
         * @example 2024-02-01T09:00:00Z
         */
        date: string;
        /** @description Only return trips where bicycles are known to be allowed */
        bicycles?: boolean;
        /** @description Only return trips where dogs are known to be allowed */
        dogs?: boolean;
      };
    };
    responses: {
      /** @description A list of available train trips */
      200: {
        headers: {
          'Cache-Control': components['headers']['Cache-Control'];
          RateLimit: components['headers']['RateLimit'];
        };
        content: {
          'application/json': components['schemas']['Wrapper-Collection'] & {
            data?: (components['schemas']['Trip'] &
              components['schemas']['Links-Origin'] &
              components['schemas']['Links-Destination'])[];
          } & {
            links?: components['schemas']['Links-Self'] &
              components['schemas']['Links-Pagination'];
          };
          'application/xml': components['schemas']['Wrapper-Collection'] & {
            data?: components['schemas']['Trip'][];
          } & {
            links?: components['schemas']['Links-Self'] &
              components['schemas']['Links-Pagination'];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * List existing bookings
   * @description Returns a list of all trip bookings by the authenticated user.
   */
  'get-bookings': {
    parameters: {
      query?: {
        page?: components['parameters']['page'];
        limit?: components['parameters']['limit'];
      };
    };
    responses: {
      /** @description A list of bookings */
      200: {
        headers: {
          'Cache-Control': components['headers']['Cache-Control'];
          RateLimit: components['headers']['RateLimit'];
        };
        content: {
          'application/json': components['schemas']['Wrapper-Collection'] & {
            data?: components['schemas']['Booking'][];
          } & {
            links?: components['schemas']['Links-Self'] &
              components['schemas']['Links-Pagination'];
          };
          'application/xml': components['schemas']['Wrapper-Collection'] & {
            data?: components['schemas']['Booking'][];
          } & {
            links?: components['schemas']['Links-Self'] &
              components['schemas']['Links-Pagination'];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Create a booking
   * @description A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
   */
  'create-booking': {
    /** @description Booking details */
    requestBody: {
      content: {
        'application/json': components['schemas']['Booking'];
        'application/xml': components['schemas']['Booking'];
      };
    };
    responses: {
      /** @description Booking successful */
      201: {
        content: {
          'application/json': components['schemas']['Booking'] & {
            links?: components['schemas']['Links-Self'];
          };
          'application/xml': components['schemas']['Booking'] & {
            links?: components['schemas']['Links-Self'];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Get a booking
   * @description Returns the details of a specific booking.
   */
  'get-booking': {
    parameters: {
      path: {
        /**
         * @description The ID of the booking to retrieve.
         * @example 1725ff48-ab45-4bb5-9d02-88745177dedb
         */
        bookingId: string;
      };
    };
    responses: {
      /** @description The booking details */
      200: {
        headers: {
          'Cache-Control': components['headers']['Cache-Control'];
          RateLimit: components['headers']['RateLimit'];
        };
        content: {
          'application/json': components['schemas']['Booking'] & {
            links?: components['schemas']['Links-Self'];
          };
          'application/xml': components['schemas']['Booking'] & {
            links?: components['schemas']['Links-Self'];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Delete a booking
   * @description Deletes a booking, cancelling the hold on the trip.
   */
  'delete-booking': {
    parameters: {
      path: {
        /**
         * @description The ID of the booking to retrieve.
         * @example 1725ff48-ab45-4bb5-9d02-88745177dedb
         */
        bookingId: string;
      };
    };
    responses: {
      /** @description Booking deleted */
      204: {
        content: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Pay for a Booking
   * @description A payment is an attempt to pay for the booking, which will confirm the booking for the user and enable them to get their tickets.
   */
  'create-booking-payment': {
    parameters: {
      path: {
        /**
         * @description The ID of the booking to pay for.
         * @example 1725ff48-ab45-4bb5-9d02-88745177dedb
         */
        bookingId: string;
      };
    };
    /** @description Payment details */
    requestBody: {
      content: {
        'application/json': components['schemas']['BookingPayment'];
      };
    };
    responses: {
      /** @description Payment successful */
      200: {
        headers: {
          'Cache-Control': components['headers']['Cache-Control'];
          RateLimit: components['headers']['RateLimit'];
        };
        content: {
          'application/json': components['schemas']['BookingPayment'] & {
            links?: components['schemas']['Links-Booking'];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * New Booking
   * @description Subscribe to new bookings being created, to update integrations for your users.  Related data is available via the links provided in the request.
   */
  'new-booking': {
    requestBody: {
      content: {
        /**
         * @example {
         *   "id": "efdbb9d1-02c2-4bc3-afb7-6788d8782b1e",
         *   "trip_id": "efdbb9d1-02c2-4bc3-afb7-6788d8782b1e",
         *   "passenger_name": "John Doe",
         *   "has_bicycle": true,
         *   "has_dog": true,
         *   "links": {
         *     "self": "https://api.example.com/bookings/1725ff48-ab45-4bb5-9d02-88745177dedb"
         *   }
         * }
         */
        'application/json': components['schemas']['Booking'] & {
          links?: components['schemas']['Links-Self'] &
            components['schemas']['Links-Pagination'];
        };
      };
    };
    responses: {
      /** @description Return a 200 status to indicate that the data was received successfully. */
      200: {
        content: never;
      };
    };
  };
}
